In [1]:
##Data Preprocessing

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("anime.csv")

In [7]:
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [9]:
df.drop_duplicates(inplace=True)

In [11]:
df.dropna(subset=["genre", "rating"], inplace=True)

In [15]:
df['episodes'] = pd.to_numeric(df['episodes'], errors='coerce')

In [17]:
##Feature Extraction

In [19]:
df['genre'] = df['genre'].str.lower()

In [21]:
df['genre']

0                     drama, romance, school, supernatural
1        action, adventure, drama, fantasy, magic, mili...
2        action, comedy, historical, parody, samurai, s...
3                                         sci-fi, thriller
4        action, comedy, historical, parody, samurai, s...
                               ...
12289                                               hentai
12290                                               hentai
12291                                               hentai
12292                                               hentai
12293                                               hentai
Name: genre, Length: 12017, dtype: object

In [23]:
genres = df['genre'].str.get_dummies(sep=', ')

In [25]:
genres

,action,adventure,cars,comedy,dementia,demons,drama,ecchi,fantasy,game,...,shounen ai,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri
0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,1,1,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12289,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12290,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12291,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12292,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12293,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
from sklearn.preprocessing import MinMaxScaler

In [29]:
scaler = MinMaxScaler()

In [31]:
df['rating'] = scaler.fit_transform(df[['rating']])

In [33]:
df['rating']

0        0.924370
1        0.911164
2        0.909964
3        0.900360
4        0.899160
           ...
12289    0.297719
12290    0.313325
12291    0.385354
12292    0.397359
12293    0.454982
Name: rating, Length: 12017, dtype: float64

In [35]:
features = pd.concat([genres, df['rating']], axis=1)

In [37]:
features

,action,adventure,cars,comedy,dementia,demons,drama,ecchi,fantasy,game,...,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri,rating
0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0.924370
1,1,1,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0.911164
2,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.909964
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.900360
4,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.899160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12289,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.297719
12290,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.313325
12291,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.385354
12292,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.397359
12293,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.454982

In [39]:
##Cosine Similarity Recommendation Function

In [41]:
from sklearn.metrics.pairwise import cosine_similarity

In [43]:
cos_sim = cosine_similarity(features)

In [45]:
cos_sim

array([[1.        , 0.29880771, 0.13644987, ..., 0.15085865, 0.15492584,
        0.1737458 ],
       [0.29880771, 1.        , 0.36135915, ..., 0.11708593, 0.12024259,
        0.13484933],
       [0.13644987, 0.36135915, 1.        , ..., 0.116948  , 0.12010094,
        0.13469047],
       ...,
       [0.15085865, 0.11708593, 0.116948  , ..., 1.        , 0.99994581,
        0.99824985],
       [0.15492584, 0.12024259, 0.12010094, ..., 0.99994581, 1.        ,
        0.99881138],
       [0.1737458 , 0.13484933, 0.13469047, ..., 0.99824985, 0.99881138,
        1.        ]])

In [59]:
def recommend_anime(anime_title, top_n=5):
    idx = df[df['name'].str.lower() == anime_title.lower()].index
    if idx.empty:
        return "Anime not found."
    idx = idx[0]
    sim_scores = list(enumerate(cos_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:top_n+1]
    anime_indices = [i[0] for i in sim_scores]
    return df['name'].iloc[anime_indices]

In [61]:
print(recommend_anime("Naruto", top_n=5))

615                                    Naruto: Shippuuden
1103    Boruto: Naruto the Movie - Naruto ga Hokage ni...
486                              Boruto: Naruto the Movie
1343                                          Naruto x UT
1472          Naruto: Shippuuden Movie 4 - The Lost Tower
Name: name, dtype: object

In [63]:
##Evaluation

In [65]:
from sklearn.model_selection import train_test_split

In [67]:
X_train, X_test = train_test_split(df, test_size=0.2, random_state=42)

In [73]:
def precision_recall(target, recommendations):
    target_genres = set(df[df['name'] == target]['genre'].values[0].split(', '))
    relevant = 0
    for rec in recommendations:
        rec_genres = set(df[df['name'] == rec]['genre'].values[0].split(', '))
        if target_genres & rec_genres:
            relevant += 1
    precision = relevant / len(recommendations)
    recall = relevant / len(target_genres)
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0
    return precision, recall, f1

In [75]:
target = "Naruto"
recs = recommend_anime(target, 5)
p, r, f1 = precision_recall(target, recs)

In [77]:
print(f"Precision: {p:.2f}, Recall: {r:.2f}, F1-score: {f1:.2f}")

Precision: 1.00, Recall: 1.00, F1-score: 1.00

In [ ]:
Q1. Difference between user-based and item-based collaborative filtering?

User-based: recommends items liked by similar users.

Item-based: recommends items similar to those the user already liked.

Item-based is usually more scalable and stable.